projects/03_Django/mysite/booklib/urls.py
# booklib/urls.py
from django.urls import path
from booklib import views

app_name = 'booklib'

# from booklib.views import index
urlpatterns = [
    path('',views.index, name='index'),
    path('bookdetail/',views.bookdetail,name='bookdetail'),
    path('addBook/',views.addBook,name='addBook'),
    path('delBook/<int:book_id>',views.delBook,name='delBook'),
]

projects/03_Django/mysite/booklib/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    """docstring for Book"""
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

projects/03_Django/mysite/booklib/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
# from booklib import models
from booklib.models import *

from django.urls import reverse

# Create your views here.
def index(request):
    return HttpResponse('Hello Django!')

def bookdetail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list':book_list}
    return render(request,'booklib/bookdetail.html',context)


def addBook(request):
    if request.method == 'POST':
        tmp_name = request.POST['name']
        tmp_author = request.POST['author']
        tmp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    tmp_book = Book(name=tmp_name,author=tmp_author,pub_house=tmp_pub_house,pub_date=timezone.now())
    tmp_book.save()

    # redirect
    return HttpResponseRedirect(reverse('booklib:bookdetail'))

def delBook(request,book_id):
    bookID = book_id
    Book.objects.filter(id=bookID).delete()
    return HttpResponseRedirect(reverse('booklib:bookdetail'))

projects/03_Django/mysite/booklib/templates/booklib/bookdetail.html
<!-- coding:utf-8 -->
<h1>Book List</h1>

<table>
    <tr>
        <td>书名</td>
        <td>作者</td>
        <td>出版社</td>
        <td>出版时间</td>
    </tr>
    {% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'booklib:delBook' book.id %}"> 删除</a></td>
    </tr>

{% endfor %}
</table>


<form action="{% url 'booklib:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>书名:</span><input type="text" name="name"></p>
    <p><span>作者:</span><input type="text" name="author"></p>
    <p><span>出版社:</span><input type="text" name="pub_house"></p>
    <input type="submit" value="添加">
</form>
    